### **Installing PyTorch**

In [6]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [7]:
import torch
torch.__version__

'2.13.0+cpu'

In [8]:
import torch
torch.cuda.is_available()

False

### **Create tensors**

In [6]:
import torch
tensor0d = torch.tensor(1)

tensor0d.dtype

torch.int64

#### **Tensor dtypes**

In [7]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [8]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [9]:
floatvec = tensor1d.to(torch.float32)   # change precision using .to() method
print(floatvec.dtype)

torch.float32


#### **Common PyTorch tensor operations**

In [10]:
tensor2d = torch.tensor([[1, 2, 3], 
                 [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [11]:
print(tensor2d.shape)

torch.Size([2, 3])


In [12]:
print(tensor2d.reshape(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [13]:
print(tensor2d.view(3, 2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [14]:
print(tensor2d.T)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [15]:
print(tensor2d.matmul(tensor2d.T))

tensor([[14, 32],
        [32, 77]])


In [16]:
print(tensor2d @ tensor2d.T)

tensor([[14, 32],
        [32, 77]])
