### **Installing PyTorch**

In [6]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [7]:
import torch
torch.__version__

'2.13.0+cpu'

In [8]:
import torch
torch.cuda.is_available()

False

### **Create tensors**

##### In PyTorch, a tensor is a multidimensional array (similar to a NumPy array) that stores numerical data and supports GPU acceleration and automatic differentiation.

In [14]:
import torch
tensor0d = torch.tensor(1)  # zero-dimensional tensor(scalar)
tensor1d = torch.tensor([1, 2, 3])  # one-dimensional tensor(vector)
tensor2d = torch.tensor([[1, 2],    # two-dimensional tensor(matrix)
                         [3, 4]]) 
tensor3d = torch.tensor([[[1, 2], [3, 4]],  # four-dimensional tensor
                         [[5, 6], [7, 8]]]) 

In [ ]:
tensor3d.dtype  # In PyTorch, default 64-bit integer datatype

torch.int64

#### **Tensor dtypes**

In [16]:
tensor1d = torch.tensor([1, 2, 3])  # In PyTorch, default 64-bit integer datatype
print(tensor1d.dtype)

torch.int64


In [17]:
floatvec = torch.tensor([1.0, 2.0, 3.0])    # default 32-bit float datatype
print(floatvec.dtype)

torch.float32


In [18]:
floatvec = tensor1d.to(torch.float32)   # change precision using .to() method
print(floatvec.dtype)

torch.float32


#### **Common PyTorch tensor operations**

In [ ]:
tensor2d = torch.tensor([[1, 2, 3],     # create new tensors
                         [4, 5, 6]])
print(tensor2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
print(tensor2d.shape)   # shape of a tensor

torch.Size([2, 3])


In [ ]:
print(tensor2d.reshape(3, 2))   # reshape the tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
print(tensor2d.view(3, 2))  # reshape the tensor(another way)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
print(tensor2d.T)   # transpose a tensor

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
print(tensor2d.matmul(tensor2d.T))  # multiply two matrices in pytorch

tensor([[14, 32],
        [32, 77]])


In [ ]:
print(tensor2d @ tensor2d.T)    # multiply two metrices in another way(by using @ operator)

tensor([[14, 32],
        [32, 77]])
